### ISSUE TITLE
官方最新的292也发布了，能更新下嘛

### ISSUE THREAD

**Issue by moumouren** [lzpong/RDCMan#2]
官方最新的292也发布了，能更新下嘛，感谢。
290这个偶尔有点bug不过也很好用

**Comment by zhoushaobb** [comment]
谢谢作者！感谢！
另外，官方最新的2.92也期待您的汉化更新哦！

**Comment by lzpong** [comment]
[最新版 v2.92](https://github.com/lzpong/RDCMan/releases/tag/v2.92)
@zhoushaobb 更新了
@moumouren  有bug欢迎反馈呀!
